# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Node.js CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    defaults: 
      run:
        working-directory: ./lab-corrections

    services: 
      redis:
        image: redis
        ports:
          - 6379:6379

    steps:
    - uses: actions/checkout@v4

    - name: Wait for Redis
      run: |
            for i in {1..5}; do 
              nc -z 127.0.0.1 6379 && echo Success && exit 0
              echo -n .
              sleep 1
            done
            echo Failed Waiting for Redis && exit 1
        
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
        cache-dependency-path: './lab-corrections/package-lock.json'
    - run: npm ci
    - run: npm run build --if-present
    - run: npm test
